### ISSUE TITLE
Thursday project meeting notes

### ISSUE THREAD

**Issue by sc9an** [kennyitang/BIOS735-Group3#1]
Starting this issue as a notepad for the meeting with Naim. I added below some questions I have for us and him to discuss. It seems we all are busy with exams and catching-up this week, so feel free to add any question/response to this at any point.

1. How do we design analysis based on Module 2 so that it is comparable to the methods in Module 3? For example, if we use lasso or random forest from Module 3 to select the optimal model, how should we build the proportional odds model from Module 2 so that it achieves similar purpose? How valid is it to decide the variables for the Model 2 proportional odds model based on just intuition and significance values? 
    * Or should we just have one penalized proportional odds model? But how do we incorporate knowledge from Module 2 in this analysis (because the model itself can be automated by caret)? 

2. In response to Naim's question, we can assess model predictive performance by using a reserved test data set, where we evaluate whether the model predicts the severity correctly or whether it falls into the right (dichotomized) severity category. We could potentially even use other State's car accident data for an exploratory test at the end.

3. Also just curious do we need to scale categorical/ordinal predictors as well for lasso-type of methods?

**Comment by marissaashner** [comment]
2. To add on to this, we can use some of the methods learned in class to quantify how well the model performs on the test set, such as the kappa metric, and cross validation
